'use client'
// import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import './globals.css'
import { ThemeProvider } from './components/ThemeContext';
import { Spinner } from '@chakra-ui/react';
import { useEffect, useState } from 'react';

const outfit = Outfit({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'sendomoka — Personal Website of Jehian',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [ loading, setLoading ] = useState(true)
  useEffect(() => {
    const handleload = () => {
      setTimeout(() => {
        setLoading(false)
      }, 2000)
    }
    window.addEventListener('load', handleload)
    return () => window.removeEventListener('load', handleload)
  }, [])
  // if (loading) {
  //   return (
  //     <Spinner
  //       position='fixed'
  //       top='50%'
  //       left='50%'
  //       transform='translate(-50%, -50%)'
  //       thickness="4px"
  //       speed="0.65s"
  //       emptyColor="gray.200"
  //       color="blue.500"
  //       size="xl"
  //     />
  //   )
  // }
  return (
    <html lang="en">
      <ThemeProvider>
      <body className={outfit.className}>
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
      </ThemeProvider>
    </html>
  )
}
